# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarChain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarChain
  pod 'Web3'
  pod 'Web3/PromiseKit'
  pod 'Web3/ContractABI'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
end
